### ISSUE TITLE
Default value of :USE for DEFPACKAGE is implementation dependent.

### ISSUE THREAD

**Issue by hyotang666** [myaosato/myaosato.github.io#2]
> この状態ではcl:in-packageがパッケージFOOにinternされていないからです.

[DEFPACKAGEに:USEがない場合は処理系依存です。](http://www.lispworks.com/documentation/HyperSpec/Body/m_defpkg.htm)

可搬的に:CLを使わないPACKAGEを定義したい場合は明示的に(:USE)と指定すればokです。

ちなみに処理系は何をお使いでしょうか？

> FOO> (defun + (&rest numbers) (declare (ignore numbers)) 0)
> WARNING: redefining COMMON-LISP:+ in DEFUN
> +

これも処理系によりけりで、PACKAGE-LOCK機構を持つ処理系ならエラーになるようです。
（具体的には少なくともSBCLではエラー。）

**Comment by myaosato** [comment]
なるほど。そうなんですね。ありがとうございます。

:useの件、うまく書き直す事考えます。

PACKAGE-LOCK機構に関する部分は、私の考慮漏れです。
書き直そうと思います。

処理系はSBCL使ってます。(手元で試した時に何も考えずにエラーを解消させてしまっていた。

**Comment by hyotang666** [comment]
重箱の隅をつつくようなissueで心苦しくもあったのですがパッケージに関する記事は少ないのが実情かと思います。
[実践Common Lisp](http://www.gigamonkeys.com/book/programming-in-the-large-packages-and-symbols.html#package-gotchas)にも

> いったん慣れてしまえば、パッケージについて考えることは少なくなるだろう。
> 考えるべきことも多くない。
> それでもパッケージには、新人Lispプログラマが実際よりも複雑でとっつきにくいと思わせるような悩みどころがいくつかある。

とある通り、喉元過ぎれば熱さを忘れるというやつで、何が分からなかったのか分からなくなるので記事にしづらいという側面もあるかと存じます。

今回の記事は[このツイート](https://twitter.com/darjeeling743/status/1305461976861032448)を受けてのものと思っています。
私も触発されて[書きました](https://hyotang666.github.io/archives/package)。
逆引きCommon Lispが[更新された](https://lisphub.jp/common-lisp/cookbook/index.cgi?%e6%a8%99%e6%ba%96%e7%b5%84%e3%81%bf%e8%be%bc%e3%81%bf%e3%81%ae%e3%82%b7%e3%83%b3%e3%83%9c%e3%83%ab%e3%82%92%e4%b8%8a%e6%9b%b8%e3%81%8d%e3%81%97%e3%81%9f%e3%81%84)のも[同様のツイート](https://twitter.com/darjeeling743/status/1305461791066005505)が原因と思ってます。

なんだかんだでパッケージは分かりにくいものかと思うので、異なる視点による記事が増えるのはコミュニティにとって大変有益かと思っております。
ありがとうございました！

**Comment by myaosato** [comment]
不完全だとは思いつつ、とりあえず注記をしました。

わかりやすさを考えて、記事の構成も変えようかと思っているので、
今日明日また書き直し作業するとは思いますが、とりあえず。

https://github.com/myaosato/myaosato.github.io/commit/c40791d30b440954a3af3da2abaa4dd0171eb6b0

**Comment by myaosato** [comment]
書き直ししてたり、くたばってたりしてたら、ちょっと時間がかかりそうなので、来週末くらいまでに頑張るということで。

**Comment by myaosato** [comment]
他の方からの指摘も取り入れて、書き直しました。

また不備があったら、教えてもらえると助かります。

defpackageのオプションはまだ書いてませんが、一度このIssueはcloseします
